[tools]
"aqua:gradle/gradle" = "latest"
go = "1.23"
java = "latest"
node = "latest"
"npm:eas-cli" = "latest"
"npm:expo" = "latest"
"pipx:claude-monitor" = "latest"
"pipx:httpie" = "latest"
python = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
